# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudflare-utils" do
  name "cloudflare-utils"
  desc "Community created utilities for Cloudflare such as:

- Deleting all records in a zone
- Deleting all records in a zone except for a list of records
- Deleting all Pages deployments for a branch
- Deleting all Pages deployments for project
- Deleting all Pages deployments before or after a time

Cloudflare and the Cloudflare logo are trademarks and/or registered trademarks of Cloudflare, Inc.
"
  homepage "https://cloudflare-utils.cyberjake.xyz/"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudflare-utils"

  on_macos do
    on_intel do
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_#{version}_darwin_amd64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
      sha256 "d52bbd7b7cf20b605715191fe1b6d3b9ddf32282cd1ddc923dae9c76c38c0a5d"
    end
    on_arm do
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_#{version}_darwin_arm64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
      sha256 "47a909fc9e7f97f6f431bb10c2086078b29386006a138f72c614bd5d4b403cab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_#{version}_linux_amd64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
      sha256 "1f61012a293b34049cf4ac731e755f337f91e3fb278981364d3f5ec4148edefa"
    end
    on_arm do
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_#{version}_linux_arm64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
      sha256 "8d659c150e47ba34ef09b60cd355ff18e504fa3325a58f396f10ba0ac5a70f78"
    end
  end

  # No zap stanza required
end
