# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudflare-utils" do
  version "1.8.1"

  on_macos do
    on_intel do
      sha256 "43963ba4d2f3424e71e13e7c5d898fc8cafb0a02598143d777ff5c155f9e56fd"
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_darwin_amd64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
    end
    on_arm do
      sha256 "f3eb64926e58b10841b7796c982ec73a7d6208280c717404f258adc84e1b12b4"
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_darwin_arm64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
    end
  end

  on_linux do
    on_intel do
      sha256 "170e76baf02062f9d80e7e20fcf9d2b9574c9eb87b0e19908e595401936a2016"
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_linux_amd64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
    end
    on_arm do
      sha256 "f8a08331fb4fbffa07d509bee10081ce7acdacfad6bc388ee9df9b7c5d121a8c"
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_linux_arm64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
    end
  end

  name "cloudflare-utils"
  desc "Community created utilities for Cloudflare such as:

- Deleting all records in a zone
- Deleting all records in a zone except for a list of records
- Deleting all Pages deployments for a branch
- Deleting all Pages deployments for project
- Deleting all Pages deployments before or after a time

Cloudflare and the Cloudflare logo are trademarks and/or registered trademarks of Cloudflare, Inc.
"
  homepage "https://cloudflare-utils.cyberjake.xyz/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudflare-utils"

  # No zap stanza required

end
