# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudflare-utils" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "b09a8cf779ffb9801e739e506f3f07a08d8952f6c67d1a40863fb2db86c69278"
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_darwin_amd64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
    end
    on_arm do
      sha256 "bcc622f58273aafa1b849ea4b8d47381146e05f23f673bd78d4c27d5c8ea33cd"
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_darwin_arm64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
    end
  end

  on_linux do
    on_intel do
      sha256 "21132bed81eb432e77b4b360f2a3dc739fc7b234cf4a72c0ca5aa1af4bd33ed6"
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_linux_amd64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
    end
    on_arm do
      sha256 "47e08185a429d7c882e407b708b47eb0ec12613f0814f3baff91a9a678a101af"
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v#{version}/cloudflare-utils_linux_arm64.tar.xz",
        verified: "github.com/Cyb3r-Jak3/cloudflare-utils"
    end
  end

  name "cloudflare-utils"
  desc "Community created utilities for Cloudflare such as:

- Deleting all records in a zone
- Deleting all records in a zone except for a list of records
- Deleting all Pages deployments for a branch
- Deleting all Pages deployments for project
- Deleting all Pages deployments before or after a time

Cloudflare and the Cloudflare logo are trademarks and/or registered trademarks of Cloudflare, Inc.
"
  homepage "https://cloudflare-utils.cyberjake.xyz/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudflare-utils"
  bash_completion "./completions/cloudflare-utils.bash"
  fish_completion "./completions/cloudflare-utils.fish"
  zsh_completion "./completions/cloudflare-utils.zsh"

  # No zap stanza required

end
