# This file was generated by GoReleaser. DO NOT EDIT.
cask "email-backup-tool" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "408996e109a0cfa8e73c44e1a99af19a503673d7ae4f603eccbfdd49f476ab3f"
      url "https://github.com/Cyb3r-Jak3/email-backup-tool/releases/download/v#{version}/email-backup-tool_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "894322ea3d42d35e5012348344b9d63cea9e7bcd2966d74bd875f00188b6b911"
      url "https://github.com/Cyb3r-Jak3/email-backup-tool/releases/download/v#{version}/email-backup-tool_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d6231e844e56fcbc143b83351c354aa0b167d21ad87d54fac015a1f2141de228"
      url "https://github.com/Cyb3r-Jak3/email-backup-tool/releases/download/v#{version}/email-backup-tool_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "35b441f1c234a2314cf860e4282fb79832e918d8d67329a6568fe55ccd5843a1"
      url "https://github.com/Cyb3r-Jak3/email-backup-tool/releases/download/v#{version}/email-backup-tool_linux_amd64.tar.gz"
    end
  end

  name "email-backup-tool"
  desc "A tool to back up your email from an IMAP server, encrypt it, and store it in a cloud storage service.
Supports incremental backups, attachments, and multiple mailboxes. Written in Go.
Can encrypt backups using age or OpenPGP, and store them in S3-compatible storage.
"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "email-backup-tool"
  bash_completion "./completions/email-backup-tool.bash"
  fish_completion "./completions/email-backup-tool.fish"
  zsh_completion "./completions/email-backup-tool.zsh"

  # No zap stanza required
end
