# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudflareUtils < Formula
  desc "Community created utilities for Cloudflare such as:

- Deleting all records in a zone
- Deleting all records in a zone except for a list of records
- Deleting all Pages deployments for a branch
- Deleting all Pages deployments for project
- Deleting all Pages deployments before or after a time

Cloudflare and the Cloudflare logo are trademarks and/or registered trademarks of Cloudflare, Inc. in the United States and other jurisdictions.
"
  homepage "https://cloudflare-utils.cyberjake.xyz/"
  version "1.3.2-rc1"
  license "Apache 2.0"

  on_macos do
    on_intel do
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.3.2-rc1/cloudflare-utils_1.3.2-rc1_darwin_amd64.tar.xz"
      sha256 "f70bfb0de8a51cfad65cf757f59af1d68ebcc22f75e651e75af97b484a84d1ff"

      def install
        bin.install "cloudflare-utils"
      end
    end
    on_arm do
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.3.2-rc1/cloudflare-utils_1.3.2-rc1_darwin_arm64.tar.xz"
      sha256 "1d849fca31124aa4ac94ac0d8ed1e376e816cd5f1bfc4c64282b92844793ac0d"

      def install
        bin.install "cloudflare-utils"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.3.2-rc1/cloudflare-utils_1.3.2-rc1_linux_amd64.tar.xz"
        sha256 "a95b601f5a6a535a1dff8596a4165abf9f232c3e30675589a8f318563b811ed1"

        def install
          bin.install "cloudflare-utils"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.3.2-rc1/cloudflare-utils_1.3.2-rc1_linux_armv6.tar.xz"
        sha256 "5a5c7c9f713c80efe2a71adedd55da9e2c2e3a0da675c9a388cc4b5b8ec3dae4"

        def install
          bin.install "cloudflare-utils"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.3.2-rc1/cloudflare-utils_1.3.2-rc1_linux_arm64.tar.xz"
        sha256 "80c7ef02d6f8aea1efe6768d01323940b6b19ce2d1b36fe9bc40d11082a33e98"

        def install
          bin.install "cloudflare-utils"
        end
      end
    end
  end
end
