# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudflareUtils < Formula
  desc "Community created utilities for Cloudflare such as:

- Deleting all records in a zone
- Deleting all records in a zone except for a list of records
- Deleting all Pages deployments for a branch
- Deleting all Pages deployments for project
- Deleting all Pages deployments before or after a time

Cloudflare and the Cloudflare logo are trademarks and/or registered trademarks of Cloudflare, Inc.
"
  homepage "https://cloudflare-utils.cyberjake.xyz/"
  version "1.4.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.4.2/cloudflare-utils_1.4.2_darwin_amd64.tar.xz"
      sha256 "4bfeb5dc092b89e7c7e1fed7332f65932902a4df0b82ecef16201c26b5612d59"

      def install
        bin.install "cloudflare-utils"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.4.2/cloudflare-utils_1.4.2_darwin_arm64.tar.xz"
      sha256 "0f9fd7bdd54976d09f94b874531c746b727e3317fc8b3f87d30bbcd05e6d459a"

      def install
        bin.install "cloudflare-utils"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.4.2/cloudflare-utils_1.4.2_linux_amd64.tar.xz"
        sha256 "a9186917917bab37f80b20bd5b32bd73f5eeb9cbfb46d45da3d53f090f023b01"

        def install
          bin.install "cloudflare-utils"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.4.2/cloudflare-utils_1.4.2_linux_armv6.tar.xz"
        sha256 "edea490f817b4d80cbdf3ecd3685e9ce6eed066029fcf7021d561c13b025b7b9"

        def install
          bin.install "cloudflare-utils"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.4.2/cloudflare-utils_1.4.2_linux_arm64.tar.xz"
        sha256 "644a8979eedba942e6231803d5e471ff61ad229cdf9e52d1165cba6f478421b3"

        def install
          bin.install "cloudflare-utils"
        end
      end
    end
  end
end
