# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudflareUtils < Formula
  desc "Community created utilities for Cloudflare such as:

- Deleting all records in a zone
- Deleting all records in a zone except for a list of records
- Deleting all Pages deployments for a branch
- Deleting all Pages deployments for project
- Deleting all Pages deployments before or after a time

Cloudflare and the Cloudflare logo are trademarks and/or registered trademarks of Cloudflare, Inc.
"
  homepage "https://cloudflare-utils.cyberjake.xyz/"
  version "1.3.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.3.4/cloudflare-utils_1.3.4_darwin_amd64.tar.xz"
      sha256 "4890a5c139b0b6ee821fcdb5102f84616298ef5ab9b4973474c8727636930a6c"

      def install
        bin.install "cloudflare-utils"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.3.4/cloudflare-utils_1.3.4_darwin_arm64.tar.xz"
      sha256 "c3fe1e9e14570157d223caf23526f68b300eee8199888eaabb0ff9f67f391d6b"

      def install
        bin.install "cloudflare-utils"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.3.4/cloudflare-utils_1.3.4_linux_amd64.tar.xz"
        sha256 "d34a2d434f1ae2f7812bea0880b8c96ec74c3b6d75f5a7f6ee744a8146f3ff83"

        def install
          bin.install "cloudflare-utils"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.3.4/cloudflare-utils_1.3.4_linux_armv6.tar.xz"
        sha256 "d37d13b080227063fb719efe52221bfe00b70314c124b3b73196665f1bd49fd1"

        def install
          bin.install "cloudflare-utils"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/download/v1.3.4/cloudflare-utils_1.3.4_linux_arm64.tar.xz"
        sha256 "36ce4258f7291011afb3f98270e5cb50bfea41c01185623732014c86d5ad6c99"

        def install
          bin.install "cloudflare-utils"
        end
      end
    end
  end
end
