# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoAwsConsole < Formula
  desc "Simple cli tool for opening the AWS console in your default browser.
"
  homepage "https://github.com/Cyb3r-Jak3/go-aws-console"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.2/go-aws-console_0.1.2_darwin_amd64.tar.gz"
      sha256 "6f6b0a1aadd5ed9be8f049c24680b7a755014791b6d98447d44f67eba246817b"

      def install
        bin.install "go-aws-console"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.2/go-aws-console_0.1.2_darwin_arm64.tar.gz"
      sha256 "b16ad2df74662dedbc9408e01438ef0b16772aa06ae4e6c0cf61035a2d1f5847"

      def install
        bin.install "go-aws-console"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.2/go-aws-console_0.1.2_linux_amd64.tar.gz"
        sha256 "50ffa24d176ce5920577efdba3b0edbb98692302c248af22bf944b1d833b98b8"

        def install
          bin.install "go-aws-console"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.2/go-aws-console_0.1.2_linux_armv6.tar.gz"
        sha256 "e4575d66708147458b78c011de293dd1e8f57153a696796ea74eff605d544a14"

        def install
          bin.install "go-aws-console"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.2/go-aws-console_0.1.2_linux_arm64.tar.gz"
        sha256 "37fbc2fbbffcaec57931e62894db0415ffc92c3f8b9386dc5366ca28af8ec0aa"

        def install
          bin.install "go-aws-console"
        end
      end
    end
  end
end
