# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoAwsConsole < Formula
  desc "Simple cli tool for opening the AWS console in your default browser."
  homepage "https://github.com/Cyb3r-Jak3/go-aws-console"
  version "0.1.3-rc5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.3-rc5/go-aws-console_0.1.3-rc5_darwin_amd64.tar.gz"
      sha256 "30b16dcbbd088010a7b55285dfc2d3ee138980634b0c8f30de23dc4c047a23e7"

      def install
        bin.install "go-aws-console"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.3-rc5/go-aws-console_0.1.3-rc5_darwin_arm64.tar.gz"
      sha256 "97967e17fa0d04c634cbc59331e903a9d46fd4f53d744426a9bb32df9f0938ff"

      def install
        bin.install "go-aws-console"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.3-rc5/go-aws-console_0.1.3-rc5_linux_amd64.tar.gz"
        sha256 "88834c862952eb4f9cd4b21cf3b37708414b065af63e53cf79b25b5242272683"

        def install
          bin.install "go-aws-console"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.3-rc5/go-aws-console_0.1.3-rc5_linux_armv6.tar.gz"
        sha256 "ff5cb6207efa4e1a9e36074ba7d688d2586ad985cd565729d2e516669587d10e"

        def install
          bin.install "go-aws-console"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.3-rc5/go-aws-console_0.1.3-rc5_linux_arm64.tar.gz"
        sha256 "23384d4c1d3f9820654e900e731fca5baff21ba9eef2a27c7b044db3aedc66f6"

        def install
          bin.install "go-aws-console"
        end
      end
    end
  end
end
