# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoAwsConsole < Formula
  desc "Simple cli tool for opening the AWS console in your default browser."
  homepage "https://github.com/Cyb3r-Jak3/go-aws-console"
  version "0.1.3-rc4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.3-rc4/go-aws-console_0.1.3-rc4_darwin_amd64.tar.gz"
      sha256 "c53a8832fff7e5d958ee2ab504b2d673e42bf35515c5625280d96166f256944f"

      def install
        bin.install "go-aws-console"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.3-rc4/go-aws-console_0.1.3-rc4_darwin_arm64.tar.gz"
      sha256 "016b98cf88c8aafa6b3bfdc1dbd2ee38ead2a8964de4ce4954532b521a45a847"

      def install
        bin.install "go-aws-console"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.3-rc4/go-aws-console_0.1.3-rc4_linux_amd64.tar.gz"
        sha256 "d3183b505c12e43183016b6bafdb2d6e6094695de4348c6b23feddbb1244e5e2"

        def install
          bin.install "go-aws-console"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.3-rc4/go-aws-console_0.1.3-rc4_linux_armv6.tar.gz"
        sha256 "6d49696cf9b370e45258add76c8aa369d8e7c8fea73faa6b4d53fe26c002665b"

        def install
          bin.install "go-aws-console"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Cyb3r-Jak3/go-aws-console/releases/download/v0.1.3-rc4/go-aws-console_0.1.3-rc4_linux_arm64.tar.gz"
        sha256 "979132f83b14975e6470e224881d7b7e71ded5a61feaf67c2c28763781ee2a7a"

        def install
          bin.install "go-aws-console"
        end
      end
    end
  end
end
